protoc -I=./proto --python_out=./python ./proto/esriPBuffer/EsriExtendedTypes/EsriExtendedTypes.proto
protoc -I=./proto --python_out=./python ./proto/esriPBuffer/EsriTypes.proto
protoc -I=./proto --python_out=./python ./proto/esriPBuffer/ObjectIdentifierSet.proto
protoc -I=./proto --python_out=./python ./proto/esriPBuffer/graph/DeleteDomainResponse.proto
protoc -I=./proto --python_out=./python ./proto/esriPBuffer/graph/DeleteFieldResponse.proto
protoc -I=./proto --python_out=./python ./proto/esriPBuffer/graph/AddNamedTypesRequest.proto
protoc -I=./proto --python_out=./python ./proto/esriPBuffer/graph/QueryRequest.proto
protoc -I=./proto --python_out=./python ./proto/esriPBuffer/graph/AddDomainResponse.proto
protoc -I=./proto --python_out=./python ./proto/esriPBuffer/graph/ApplyEditsResponse.proto
protoc -I=./proto --python_out=./python ./proto/esriPBuffer/graph/AddDomainRequest.proto
protoc -I=./proto --python_out=./python ./proto/esriPBuffer/graph/UpdateFieldRequest.proto
protoc -I=./proto --python_out=./python ./proto/esriPBuffer/graph/DeleteIndexesRequest.proto
protoc -I=./proto --python_out=./python ./proto/esriPBuffer/graph/UpdateFieldResponse.proto
protoc -I=./proto --python_out=./python ./proto/esriPBuffer/graph/DeleteNamedTypeResponse.proto
protoc -I=./proto --python_out=./python ./proto/esriPBuffer/graph/AddIndexesRequest.proto
protoc -I=./proto --python_out=./python ./proto/esriPBuffer/graph/AddFieldsRequest.proto
protoc -I=./proto --python_out=./python ./proto/esriPBuffer/graph/EsriGraphTypes.proto
protoc -I=./proto --python_out=./python ./proto/esriPBuffer/graph/DeleteIndexesResponse.proto
protoc -I=./proto --python_out=./python ./proto/esriPBuffer/graph/DeleteFieldRequest.proto
protoc -I=./proto --python_out=./python ./proto/esriPBuffer/graph/UpdateNamedTypeResponse.proto
protoc -I=./proto --python_out=./python ./proto/esriPBuffer/graph/DataModelTypes.proto
protoc -I=./proto --python_out=./python ./proto/esriPBuffer/graph/UpdateDomainRequest.proto
protoc -I=./proto --python_out=./python ./proto/esriPBuffer/graph/UpdateDomainResponse.proto
protoc -I=./proto --python_out=./python ./proto/esriPBuffer/graph/SearchQueryRequest.proto
protoc -I=./proto --python_out=./python ./proto/esriPBuffer/graph/AddIndexesResponse.proto
protoc -I=./proto --python_out=./python ./proto/esriPBuffer/graph/ApplyEditsRequest.proto
protoc -I=./proto --python_out=./python ./proto/esriPBuffer/graph/AddFieldsResponse.proto
protoc -I=./proto --python_out=./python ./proto/esriPBuffer/graph/QueryDataModelResponse.proto
protoc -I=./proto --python_out=./python ./proto/esriPBuffer/graph/UpdateNamedTypeRequest.proto
protoc -I=./proto --python_out=./python ./proto/esriPBuffer/graph/AddNamedTypesResponse.proto
protoc -I=./proto --python_out=./python ./proto/esriPBuffer/graph/QueryResponse.proto
